services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      APPETO_DB_USERNAME: ${DB_USER}
      APPETO_DB_PASSWORD: ${DB_PASS}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
